//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Career_Rescue.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Listing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job_Listing()
        {
            this.Job_Applied = new HashSet<Job_Applied>();
        }
    
        public int Job_id { get; set; }
        public int Employer_id { get; set; }
        public string job_Title { get; set; }
        public string job_Description { get; set; }
        public string job_Skills { get; set; }
        public string education_level { get; set; }
        public string how_to_apply { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
    
        public virtual Employer Employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Applied> Job_Applied { get; set; }
    }
}
