//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Career_Rescue.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Applied
    {
        public int id { get; set; }
        public int Member_id { get; set; }
        public int Job_id { get; set; }
        public Nullable<System.DateTime> date_applied { get; set; }
        public string job_status { get; set; }
    
        public virtual Job_Listing Job_Listing { get; set; }
        public virtual Member Member { get; set; }
    }
}
